CRITICAL - 2025-06-25 17:43:18 --> ErrorException: Undefined array key "hub"
[Method: POST, Route: userlogin]
in APPPATH\Controllers\LoginController.php on line 47.
 1 APPPATH\Controllers\LoginController.php(47): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "hub"', 'C:\\xampp\\htdocs\\churchapp\\app\\Controllers\\LoginController.php', 47)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LoginController->login()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-25 18:13:23 --> mysqli_sql_exception: Unknown column 'photo_url' in 'field list' in C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\churchapp\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\churchapp\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\churchapp\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\churchapp\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\churchapp\app\Controllers\FamilyController.php(31): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(933): App\Controllers\FamilyController->store()
#9 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
#10 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\churchapp\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\churchapp\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\churchapp\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-25 18:13:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
[Method: POST, Route: family/store]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:23 --> [Caused by] mysqli_sql_exception: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-25 18:13:32 --> mysqli_sql_exception: Unknown column 'photo_url' in 'field list' in C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\churchapp\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\churchapp\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\churchapp\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\churchapp\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\churchapp\app\Controllers\FamilyController.php(31): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(933): App\Controllers\FamilyController->store()
#9 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
#10 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\churchapp\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\churchapp\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\churchapp\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-25 18:13:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
[Method: POST, Route: family/store]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdf\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdf\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:32 --> [Caused by] mysqli_sql_exception: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdf\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdf\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdf\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-25 18:13:38 --> mysqli_sql_exception: Unknown column 'photo_url' in 'field list' in C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\churchapp\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\churchapp\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\churchapp\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\churchapp\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\churchapp\app\Controllers\FamilyController.php(31): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(933): App\Controllers\FamilyController->store()
#9 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
#10 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\churchapp\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\churchapp\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\churchapp\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-25 18:13:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
[Method: POST, Route: family/store]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdffdsssssssssssssssssss\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdffdsssssssssssssssssss\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:38 --> [Caused by] mysqli_sql_exception: Unknown column 'photo_url' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdffdsssssssssssssssssss\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdffdsssssssssssssssssss\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (\'eqwds\', \'dfdf\', \'dsfdf\', \'2\', \'dfsdf\', \'0983938939\', \'\', \'dfdffdsssssssssssssssssss\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`, `photo_url`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:, :photo_url:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\FamilyController.php(31): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:13:56 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "family/index.php"
[Method: GET, Route: families]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('family/index.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('family/index', [], true)
 3 APPPATH\Controllers\FamilyController.php(58): view('family/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 18:17:29 --> ErrorException: Undefined variable $menus
[Method: GET, Route: families]
in APPPATH\Views\common\menu_view.php on line 37.
 1 APPPATH\Views\common\menu_view.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $menus', 'C:\\xampp\\htdocs\\churchapp\\app\\Views\\common\\menu_view.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\churchapp\\app\\Views\\common\\menu_view.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('common/menu_view', null, true)
 5 APPPATH\Views\family\index.php(4): CodeIgniter\View\View->include('common/menu_view')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\churchapp\\app\\Views\\family\\index.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('family/index', [], true)
 9 APPPATH\Controllers\FamilyController.php(58): view('family/index', [...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->index()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 19:01:30 --> ParseError: syntax error, unexpected token ";"
[Method: GET, Route: family/create]
in APPPATH\Views\family\layouts\create.php on line 37.
 1 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('family/layouts/create', null, true)
 3 APPPATH\Views\family\create.php(6): CodeIgniter\View\View->include('family/layouts/create')
 4 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\churchapp\\app\\Views\\family\\create.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('family/create', [], true)
 7 APPPATH\Controllers\FamilyController.php(51): view('family/create', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->create()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-25 19:06:35 --> mysqli_sql_exception: Duplicate entry 'eqwds' for key 'family_code' in C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\churchapp\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\churchapp\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\churchapp\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\churchapp\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\churchapp\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\churchapp\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\churchapp\app\Controllers\FamilyController.php(70): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(933): App\Controllers\FamilyController->store()
#9 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
#10 C:\xampp\htdocs\churchapp\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\churchapp\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\churchapp\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\churchapp\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-25 19:06:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'eqwds' for key 'family_code'
[Method: POST, Route: family/store]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\FamilyController.php(70): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 19:06:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'eqwds' for key 'family_code'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (\'eqwds\', \'dfdf\', \'3\', \'3\', \'33\', \'323\', \'\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (\'eqwds\', \'dfdf\', \'3\', \'3\', \'33\', \'323\', \'\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\FamilyController.php(70): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-25 19:06:35 --> [Caused by] mysqli_sql_exception: Duplicate entry 'eqwds' for key 'family_code'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (\'eqwds\', \'dfdf\', \'3\', \'3\', \'33\', \'323\', \'\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (\'eqwds\', \'dfdf\', \'3\', \'3\', \'33\', \'323\', \'\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (\'eqwds\', \'dfdf\', \'3\', \'3\', \'33\', \'323\', \'\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `families` (`family_code`, `family_name`, `head_of_family`, `members_count`, `address`, `contact_number`, `registered_on`) VALUES (:family_code:, :family_name:, :head_of_family:, :members_count:, :address:, :contact_number:, :registered_on:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\FamilyController.php(70): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FamilyController->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FamilyController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
